
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique


  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - relationships:
              to: ref('my_first_dbt_model')
              field: id

  - name: customer_with_orders
    description: "customer_with_orders"
    columns:
      - name: C_CUSTKEY
        description: "The primary key for this table"
        tests:
          - not_null

  - name: cumulative_orders_by_date
    description: "cumulative_orders_by_date"
    columns:
      - name: O_ORDERDATE
        description: "The primary key for this table"
        tests:
          - unique

  - name: dates
  - name: incremental_time

  - name: playing_with_tests
    description: "cumulative_orders_by_date"
    columns:
      - name: c_custkey
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

      - name: c_mktsegment
        description: "The primary key for this table"
        tests:
          - accepted_values:
              values: ['BUILDING', 'AUTOMOBILE', 'MACHINERY', 'HOUSEHOLD', 'FURNITURE']
